[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "project_nabu"
version = "0.0.1"
description = "Multispectral processing software."
readme = "README.md"
requires-python = ">=3.9"
keywords = ["multispectral"]
license = {text = "MIT"}
authors = [ { name = "Afonso Oliveira", email = "afe.oliveira@campus.fct.unl.pt" } ]
dependencies = [ "numpy", "GDAl", "richdem"]

[project.entry-points."composite.basic"]
rgb = "project_nabu.rgb:rgb"
cir = "project_nabu.cir:cir"

[project.entry-points."index.vegetation"]
ndvi = "project_nabu.vegetation_indices:ndvi"