[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "project_nabu"
version = "0.0.1"
description = "Multispectral processing software."
readme = "README.md"
requires-python = ">=3.9"
keywords = ["multispectral"]
license = {text = "MIT"}
authors = [ { name = "Afonso Oliveira", email = "afe.oliveira@campus.fct.unl.pt" } ]
dependencies = []

[project.entry-points."composite.base"]
rgb = "project_nabu.composite_base:rgb"
cir = "project_nabu.composite_base:cir"

[project.entry-points."index.base"]
sr = "project_nabu.index_base:sr"
ndvi = "project_nabu.index_base:ndvi"
dvi = "project_nabu.index_base:dvi"
rdvi = "project_nabu.index_base:rdvi"
msr = "project_nabu.index_base:msr"
gndvi = "project_nabu.index_base:gndvi"
gari = "project_nabu.index_base:gari"
idvi = "project_nabu.index_base:idvi"
ndre = "project_nabu.index_base:ndre"
dvi2 = "project_nabu.index_base:dvi2"
grvi = "project_nabu.index_base:grvi"
ndwi = "project_nabu.index_base:ndwi"
ari = "project_nabu.index_base:ari"
mari = "project_nabu.index_base:mari"
evi = "project_nabu.index_base:evi"
evi2 = "project_nabu.index_base:evi2"
savi = "project_nabu.index_base:savi"
msavi = "project_nabu.index_base:msavi"
osavi = "project_nabu.index_base:osavi"
tavi = "project_nabu.index_base:tavi"
rei = "project_nabu.index_base:rei"