name: Documentation
on:
  push:
    tags: 'v*'
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build Documentation
        run: |
          pip3 install --upgrade pip
          pip3 install .[devel]
          pdoc --docformat=google -o docs rforge
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
